# -*- coding: utf-8 -*-
"""Sensitivity analysis for the minimum dependency set s_i.

This script evaluates two choices on the irregular 16-region topology:
1. fixed integer thresholds s_i in {0, 1, 2};
2. degree-proportional thresholds s_i = ceil(alpha |N_i|).

No intermediate CSV files are generated by this wrapper. Per-trial ADMM output
files generated by the solver are only read and overwritten by the next run.
"""

import json
import math
import os
import shutil
import subprocess
import time
from pathlib import Path

import pandas as pd


BASE_DIR = Path(__file__).resolve().parent
PYTHON = os.environ.get("PYTHON", "/usr/bin/python3")
MPIEXEC = (
    os.environ.get("MPIEXEC")
    or shutil.which("mpiexec")
    or str(Path.home() / "Library" / "Python" / "3.9" / "bin" / "mpiexec")
)
ASYNC_SCRIPT = BASE_DIR / "RE_Asynchronous.py"
CENTRALIZED_SCRIPT = BASE_DIR / "Centralized_cost.py"

DATASET = "need_data_N16"
NUM_NODES = 16
N_TRIALS = int(os.environ.get("N_TRIALS", "5"))
FIXED_TAU = int(os.environ.get("FIXED_TAU", "16"))

IRREGULAR16_TOPOLOGY = {
    "0": [1, 2, 3, 5, 8, 12],
    "1": [0, 2],
    "2": [0, 1, 4, 6],
    "3": [0, 4, 7, 10],
    "4": [2, 3, 5],
    "5": [0, 4, 6, 11],
    "6": [2, 5, 7],
    "7": [3, 6, 15],
    "8": [0, 9, 10, 12, 13],
    "9": [8, 10],
    "10": [3, 8, 9, 11, 14],
    "11": [5, 10, 12],
    "12": [0, 8, 11, 13, 15],
    "13": [8, 12, 14],
    "14": [10, 13, 15],
    "15": [7, 12, 14],
}

SETTINGS = [
    # ("s=0", {"S_MODE": "fixed", "MIN_DEP_SET": "0"}),
    # ("s=1", {"S_MODE": "fixed", "MIN_DEP_SET": "1"}),
    ("s=2", {"S_MODE": "fixed", "MIN_DEP_SET": "2"}),
    ("alpha=0.25", {"S_MODE": "formula_alpha", "ALPHA_DEP": "0.25"}),
    ("alpha=0.50", {"S_MODE": "formula_alpha", "ALPHA_DEP": "0.50"}),
    ("alpha=0.75", {"S_MODE": "formula_alpha", "ALPHA_DEP": "0.75"}),
    ("alpha=1.00", {"S_MODE": "formula_alpha", "ALPHA_DEP": "1.00"}),
]

COMMON_ENV = {
    "BASE_DIR": str(BASE_DIR),
    "TOPOLOGY": json.dumps(IRREGULAR16_TOPOLOGY),
    "SCENARIO": "4",
    "MAX_ITER": "3500",
    "MAX_LAG": str(FIXED_TAU),
    "RHO_STRATEGY": "fixed",
    "RHO_FIXED": "160",
    "PROX_RATIO": "1.5",
    "NORMAL_SLEEP": "0.005",
    "SLOW_SLEEP": "0.04",
    "SLOW_RATIO": "0.25",
    "CONGESTION_JITTER_STD": "0.003",
    "CONV_EPS_ABS": "0.01",
    "CONV_EPS_REL": "0.01",
    "CONV_STABLE_NEED": "6",
    "GRB_THREADS": "1",
}

TEMP_OUTPUTS = [
    "admm_async_auxu_metrics.csv",
    "admm_async_auxu_rank_summary.csv",
    "admm_async_auxu_obj_trace.csv",
    "admm_trace_async.csv",
    "admm_trace_async_delay.csv",
    "admm_trace_async_undelay.csv",
    "admm_async_auxu_final_x.pkl",
]


def parse_centralized(text):
    for line in text.splitlines():
        if "总目标函数值" in line or "模型 objective" in line:
            return float(line.split(":")[-1].strip())
    raise RuntimeError("Failed to parse centralized objective:\n" + text[-2000:])


def cleanup_temp_outputs():
    for name in TEMP_OUTPUTS:
        path = BASE_DIR / name
        if path.exists():
            path.unlink()


def compute_centralized():
    env = os.environ.copy()
    env.update({"BASE_DIR": str(BASE_DIR), "TOPOLOGY": json.dumps(IRREGULAR16_TOPOLOGY)})
    result = subprocess.run(
        [PYTHON, str(CENTRALIZED_SCRIPT), DATASET],
        env=env,
        capture_output=True,
        text=True,
        timeout=240,
        check=False,
    )
    return parse_centralized(result.stdout + result.stderr)


def s_values(setting_env):
    degrees = {int(i): len(nbrs) for i, nbrs in IRREGULAR16_TOPOLOGY.items()}
    if setting_env["S_MODE"] == "fixed":
        s = int(setting_env["MIN_DEP_SET"])
        return {i: s for i in range(NUM_NODES)}
    alpha = float(setting_env["ALPHA_DEP"])
    return {i: max(1, int(math.ceil(alpha * degrees[i]))) for i in range(NUM_NODES)}


def run_one(setting_label, setting_env, trial, centralized_base):
    if MPIEXEC is None:
        raise RuntimeError("mpiexec was not found. Set MPIEXEC=/path/to/mpiexec.")

    env = os.environ.copy()
    env.update(COMMON_ENV)
    env.update(setting_env)
    env["CENTRALIZED_BASE"] = str(centralized_base)

    started = time.time()
    cmd = [MPIEXEC, "-np", str(NUM_NODES), PYTHON, str(ASYNC_SCRIPT), DATASET]
    result = subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=1200)

    metrics_path = BASE_DIR / "admm_async_auxu_metrics.csv"
    rank_path = BASE_DIR / "admm_async_auxu_rank_summary.csv"
    if (
        not metrics_path.exists()
        or not rank_path.exists()
        or metrics_path.stat().st_mtime < started
        or rank_path.stat().st_mtime < started
    ):
        raise RuntimeError(
            f"Run failed for {setting_label}, trial {trial}:\n"
            + (result.stdout + result.stderr)[-3000:]
        )

    metrics = pd.read_csv(metrics_path, encoding="utf-8-sig").iloc[0].to_dict()
    row = {
        "setting": setting_label,
        "trial": trial,
        "tau": FIXED_TAU,
        "s_values": json.dumps(s_values(setting_env), ensure_ascii=False),
        "obj_total": metrics["obj_total"],
        "rel_gap_pct": metrics["rel_diff_to_centralized"] * 100.0,
        "wall_clock_total_s": metrics["wall_clock_total"],
        "avg_iter": metrics["avg_iter"],
        "avg_msg_send_cnt": metrics["avg_msg_send_cnt"],
        "iter_balance_pct": metrics["iter_balance_pct"],
        "offline_consensus_residual": metrics["offline_primal_consensus_residual"],
    }
    print(
        f"{setting_label:>10s} trial {trial}: gap={row['rel_gap_pct']:.4f}%, "
        f"time={row['wall_clock_total_s']:.3f}s, iter={row['avg_iter']:.1f}"
    )
    cleanup_temp_outputs()
    return row


def main():
    centralized_base = compute_centralized()
    rows = []
    for label, setting_env in SETTINGS:
        for trial in range(1, N_TRIALS + 1):
            rows.append(run_one(label, setting_env, trial, centralized_base))

    raw = pd.DataFrame(rows)
    order = {label: idx for idx, (label, _) in enumerate(SETTINGS)}

    summary = (
        raw.groupby(["setting", "tau", "s_values"], as_index=False)
        .agg(
            rel_gap_pct=("rel_gap_pct", "mean"),
            rel_gap_pct_std=("rel_gap_pct", "std"),
            wall_clock_total_s=("wall_clock_total_s", "mean"),
            wall_clock_total_s_std=("wall_clock_total_s", "std"),
            avg_iter=("avg_iter", "mean"),
            avg_msg_send_cnt=("avg_msg_send_cnt", "mean"),
            iter_balance_pct=("iter_balance_pct", "mean"),
            offline_consensus_residual=("offline_consensus_residual", "mean"),
            obj_total=("obj_total", "mean"),
        )
    )
    summary["_order"] = summary["setting"].map(order)
    summary = summary.sort_values("_order").drop(columns="_order")

    display = summary.rename(
        columns={
            "setting": r"$s_i$ setting",
            "rel_gap_pct": "Gap (%)",
            "rel_gap_pct_std": "Gap std. (%)",
            "wall_clock_total_s": "Wall-clock (s)",
            "wall_clock_total_s_std": "Time std. (s)",
            "avg_iter": "Avg. iter.",
            "avg_msg_send_cnt": "Avg. messages",
            "iter_balance_pct": "Iter. imbalance (%)",
            "offline_consensus_residual": "Consensus residual",
        }
    )
    display_cols = [
        r"$s_i$ setting",
        "Gap (%)",
        "Wall-clock (s)",
        "Avg. iter.",
        "Avg. messages",
        "Iter. imbalance (%)",
        "Consensus residual",
    ]

    print("\nFixed-straggler minimum-dependency sensitivity, averaged over "
          f"{N_TRIALS} trials (tau={FIXED_TAU})")
    print(display[display_cols].round(4).to_string(index=False))


if __name__ == "__main__":
    main()
